### ISSUE TITLE
Feature request : Save projects and sequences

### ISSUE THREAD

**Issue by sub26nico** [chronopoulos/ziggurat#1]
ziggurat seems not able to save sequence and project, it would be a nice feature.

**Comment by erwan35** [comment]
Hello,

Thanks for your cool work. I'd also be happy to have this feature.

Cheers
Erwan

**Comment by chronopoulos** [comment]
thanks for your interest! i have an experimental branch in which i'm prototyping this feature. hoping it will be merged this week.. fingers crossed!

**Comment by sub26nico** [comment]
Great news. I forget one thing  in my last post, so I say it here : thanks @chronopoulos , 
ziggurat is very funny at  this state and I believe it's gonna be great in the future. 
I cross my fingers ;-)

**Comment by chronopoulos** [comment]
ok, a basic implementation of "save session" and "load session" is merged. they are currently accessed via Ctrl-S and Ctrl-O (a standard menu bar will probably appear in the future). the file format JSON, and the suggested extension is ".zig" (this will be enforced in the future). let me know if you discover any issues with this!

**Comment by sub26nico** [comment]
Thanks @chronopoulos , it's works nicely. Just one thing, when I open session, it seems to add 
the 'saved' groups in the actual session, not closed actual session and open the 'saved one'. 
For exemple, if I launch ziggurat, create 2 groups, let them empty, then Ctrl+O, choose my session 
saved previously(called 'Test' for exemple, with 2 groups) , I still have my 2 empty groups, and the 2 groups saved in 'Test' are added on the right of the UI..

**Comment by chronopoulos** [comment]
@sub26nico thanks for the report! this should now be resolved with 5e19ec893fc5c21c5691d9d1e9b4b01259e7423f

**Comment by sub26nico** [comment]
Thanks! I've tested it and it works a lot better, but 2 news things are coming : 
- the midi output are now called 'default'  in Catia when I load a session. If I create a new sequence called 'kick', Catia shows 'kick' as midi output name, I save the session .When I load this session later, 
the midi output is now called 'default'.
- I have no more the box to choose the playing mode (Free, Scene,Chain, Mutex).
Sequences are played 'Free' but no more choice to play them as 'Scene', 'Chain' or 'Mutex'.

**Comment by chronopoulos** [comment]
@sub26nico thanks for testing! i have created two new issues according to your comment. the midi port name update was an oversight on my part and should be resolved shortly. the Group Type issue is a side effect of some GUI updates that are happening now, but you can expect this to be resolved, or at least have a workaround, soon.

in the future, please open a new issue for each problem you encounter; this will help me organize my to-do list :)
