### ISSUE TITLE
Feature request :  change velocity

### ISSUE THREAD

**Issue by sub26nico** [chronopoulos/ziggurat#2]
I did not found how to change MIDI velocity, maybe it's not possible at this time.
It would be a nice feature.

**Comment by chronopoulos** [comment]
correct, velocity is currently hard-wired to 100, but soon it will be adjustable as a step-wise parameter. thanks for the request!

**Comment by sub26nico** [comment]
thanks for reply, I'm happy to hear that !

**Comment by chronopoulos** [comment]
velocity editing is now implemented with f6773bca3e75b6c80a428cb1235d3b9e1f653478:

select "Editing: Note Velocity" from the dropdown menu in the Row Editor, then you can edit velocity in the same way you edit note values (using the mousewheel).

**Comment by sub26nico** [comment]
Tested, it works fine, thanks for this new feature @chronopoulos, it's gonna be very useful.
