### ISSUE TITLE
"Load Session" fails to reproduce MIDI port names

### ISSUE THREAD

**Issue by chronopoulos** [chronopoulos/ziggurat#3]
@sub26nico [commented](https://github.com/chronopoulos/ziggurat/issues/1#issuecomment-389348855):

"the midi output are now called 'default' in Catia when I load a session. If I create a new sequence called 'kick', Catia shows 'kick' as midi output name, I save the session .When I load this session later,
the midi output is now called 'default'."

**Comment by sub26nico** [comment]
Tested, it works fine now, thanks @chronopoulos
